id: Labda_403_workflow

info:
  name: Labda 403 workflow
  author: Labda
  description: Workflow for 403 Forbidden
  tags: find, web, 403, Forbidden

workflows:
  - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-finder.yaml
    matchers-condition: and
    matchers:
      - name: forbidden
      - status: 403

        subtemplates:
          - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-bypass_xheaders.yaml
          - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-bypass_post.yaml
          - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-bypass_trace.yaml
          - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-bypass_xrewriteurl.yaml
          - template: /Users/kisgergely/nuclei-templates/coli/403_workflow/403-bypass_slash.yaml